# Generated by Django 4.2 on 2023-05-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_employee',
        ),
        migrations.AddField(
            model_name='user',
            name='is_jobseeker',
            field=models.BooleanField(default=False, verbose_name='Is jobseeker'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_recruiter',
            field=models.BooleanField(default=False, verbose_name='Is recruiter'),
        ),
    ]
