# Generated by Django 4.2.1 on 2023-05-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_app", "0003_remove_book_category_remove_skill_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="address",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="education",
            field=models.CharField(
                choices=[
                    ("Diploma", "Diploma"),
                    ("Bachelors", "Bachelors"),
                    ("Masters", "Masters"),
                    ("Phd", "Phd"),
                ],
                default="Bachelors",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="email",
            field=models.EmailField(
                default="abc@gmail.com", max_length=254, unique=True
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="experience",
            field=models.CharField(default="Fresher", max_length=30),
        ),
        migrations.AddField(
            model_name="job",
            name="salary",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(default="", upload_to="profile_images"),
        ),
    ]
